import Head from 'next/head'
import styled from 'styled-components';
import { useMediaQuery } from "react-responsive";
// import Header from '../components/Header'
import { defaultTheme } from '../theme';

const MainContainer = styled.div`
  position: relative;
  width: 100%;
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  gap: ${defaultTheme.spacing['4xs']};

`

export default function Home() {

  const isMobile = useMediaQuery({ maxWidth: 900 })

  return (
    <>
      <Head>
        <title>My Osiris</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
      </MainContainer>
    </>
  )
}
